version: "3.8"

volumes:
  redis_volume:
    driver: local

networks:
  redis:

services:
  redis:
    image: redis:7.4.1-alpine
    networks:
      - redis
    environment:
      - REDIS_PASS
    command: >
      redis-server
          --save 20 1
          --loglevel warning
          --requirepass ${REDIS_PASS}
    volumes:
      - redis_volume:/data
    healthcheck:
      test: redis-cli --pass ${REDIS_PASS} --no-auth-warning ping
      interval: 10s
      timeout: 10s
      retries: 5

  frontend-server:
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      redis:
        condition: service_healthy
    ports:
      - 3000:3000
    networks:
      - redis
    environment:
      - PRIVATE_KEY
      - RPC_URL
      - COOLDOWN_HOURS
      - NEXT_PUBLIC_HCAPTCHA_SITE_KEY
      - HCAPTCHA_SECRET
      - REDIS_URL=redis://default:${REDIS_PASS}@redis:6379
